spring:
  cassandra:
    keyspace-name: main
    username: YjpsIXJZuesHlElBbrFjAdKy
    password: xMt6qQP3mUk96njwuRIIejqGrNOgm7mZIDHkfPGMsC8Gf3PnM3kO.2EelMWiU3rZJehSoDdhfgicvBFFP0dd9fgMCCFIgvgTSbs,.4P5R95RM4XW9LYFzXkEuSRJvK7j
    schema-action: create-if-not-exists
    request:
      timeout: 10s
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s
  main:
    allow-circular-references : true

datastax.astra:
    secure-connect-bundle: secure-connect.zip 


astra.db:
      id: 59516430-3bdb-44b8-a753-8d45beb8accc-1
      region: us-east1
      keyspace: main
      application.token: AstraCS:YjpsIXJZuesHlElBbrFjAdKy:444b9f920e6cbca63d57cb91d0b20a6948fcb4fa1da1e18fd9745e933d44ff5c
